name: Deploy website
on:
  push:
    branches:
      - development
  workflow_dispatch:



jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: build and test
        id: build_test
        run: |
          echo "previous_pom_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT
          JAVA_HOME=$JAVA_HOME_17_X64 && mvn clean \
          && mvn install build-helper:parse-version \
          versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} -DgenerateBackupPoms=false
          echo "current_pom_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: bpoole6
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Dockerfile
        run: |
          POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          docker build -t bpoole6/test:$POM_VERSION .
          docker push bpoole6/test:$POM_VERSION
      - name: Commit Message
        id: commit_message
        run: echo "commit_message=\"Updating version from ${{ steps.build_test.outputs.previous_pom_version }} to ${{ steps.build_test.outputs.current_pom_version }}\"" >> $GITHUB_OUTPUT
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "AUTO-GENERATED: ${{steps.commit_message.outputs.commit_message}}"




