name: Deploy website
on:
  push:
    branches:
      - main
  workflow_dispatch:



jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}   # checkout the correct branch name
          fetch-depth: 0                # fetch the whole repo history
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: build and test
        run: |
          JAVA_HOME=$JAVA_HOME_17_X64 \
            && mvn clean install build-helper:parse-version \
            versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: bpoole6
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Dockerfile
        run: |
          POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          docker build -t bpoole6/test:$POM_VERSION
          docker push



